// This file is auto-generated by Convex
// Placeholder for development - actual file will be generated by `npx convex dev`

export const api = {
  brainScheduler: {
    getContext: "brainScheduler:getContext" as any,
    writeProposals: "brainScheduler:writeProposals" as any
  },
  social: {
    listInvites: "social:listInvites" as any,
    respondInvite: "social:respondInvite" as any,
    listSentProposals: "social:listSentProposals" as any,
    updateAvailabilitySettings: "social:updateAvailabilitySettings" as any,
    createSocialEdge: "social:createSocialEdge" as any
  },
  brainSocial: {
    getContext: "brainSocial:getContext" as any,
    writeMeetingProposal: "brainSocial:writeMeetingProposal" as any
  }
};
