// This file is auto-generated by Convex
// Placeholder for development - actual file will be generated by `npx convex dev`

export function query<T>(config: T): T { return config; }
export function mutation<T>(config: T): T { return config; }
export function httpAction<T>(handler: T): T { return handler; }
