/**
 * ID Generation Utilities
 */

import { randomBytes } from 'crypto';

/**
 * Generate a unique ID with optional prefix.
 */
export function generateId(prefix?: string): string {
  const random = randomBytes(12).toString('hex');
  const timestamp = Date.now().toString(36);
  const id = `${timestamp}-${random}`;
  return prefix ? `${prefix}_${id}` : id;
}

/**
 * Generate an idempotency key for a given operation.
 */
export function generateIdempotencyKey(
  eventId: string,
  operation: string
): string {
  return `${eventId}:${operation}:v1`;
}

/**
 * Parse an ID to extract timestamp (if generated by generateId).
 */
export function parseIdTimestamp(id: string): number | null {
  try {
    const parts = id.split('_');
    const idPart = parts.length > 1 ? parts[1] : parts[0];
    const timestampPart = idPart.split('-')[0];
    return parseInt(timestampPart, 36);
  } catch {
    return null;
  }
}
